name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t productImage .
      - name: Publish image to docker hub
        run: docker push productImage:latest


  deploy:
    needs: build
    runs-on: [aws-ec2]

    steps:
      - name: Pull image from docker hub
        run : docker pull ireshaprabodhani/productImage:latest
      - name: Delete old container
        run : docker rm -f product-catelog-container
      - name: Run docker container
        run : docker run -d -p 5000:5000 -name product-catelog-container ireshaprabodhani/productImage
        