name: CI/CD actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t product-image-catelog .

      - name: Run docker image
        run: docker run -p 5000:5000 -d product-image-catelog

      - name: Log into the docker
        run: docker login --username=ireshaprabodhani
        
      - name : Tag the docker image
        run : docker tag product-image-catelog ireshaprabodhani/product-image-catelog

      - name: Publish image to Docker Hub
        run: docker push ireshaprabodhani/product-image-catelog:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull image from Docker Hub
        run: docker pull ireshaprabodhani/product-image-catelog:latest

      - name: Delete old container (if exists)
        run: docker rm -f product-catelog-container || true

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name product-catelog-container ireshaprabodhani/product-image-catelog:latest


